apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  labels:
    app: python-http-server
  annotations: 
    version: v1
    
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-http-server

  template:
    metadata:
      labels:
        app: python-http-server

    spec:
      containers:
      - name: python-server
        image: python:3.12-slim
        ports: # удалить если порт будет из переменных
        - containerPort: 8000 
        command: ["python", "-m", "http.server","8000"]

        envFrom: # пробрасывает все переменные из app-config.yam
        - configMapRef:
            name: python-config
        - secretRef:
            name: token

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3