apiVersion: v1
kind: Secret
metadata:
  name: python-secret
  namespace: default
  labels:
    app: python-http-server
type: Opaque
data:
  ACCESS_TOKEN: bXktc3VwZXItc2VjcmV0LXRva2VuLTEyMw==
  API_KEY: YW5vdGhlci1zZWNyZXQta2V5LTY3OA==